version: 0.9
ml:
  preprocessing:
    data_path: ./data/labelled_text.csv
    save_results_to: ./data/result1.pkl
    num_workers: 2
    cache: 1
  training:
    graph_mode: 0
    cache: 0

rest_api: yes