version: 0.9
log_level: INFO
ml:
  preprocessing:
    data_path: ./data/labelled_text.csv
    save_to: 
      folder: preprocessing
      filename: initial_texts.pkl
    num_workers: 10
    cache: 1
    distribute: 1
  training:
    graph_mode: 0
    cache: 0

rest_api: yes